mt7603: fix build with CONFIG_KERNEL_DYNAMIC_DEBUG=y
When building with CONFIG_KERNEL_DYNAMIC_DEBUG=y enabled, the build
fails with following error:

 <command-line>:0:37: error: redeclaration of enumerator 'IEEE80211_HW_REPORTS_TX_ACK_STATUS'
 <command-line>:0:37: note: in definition of macro 'IEEE80211_HW_TX_STATUS_NO_AMPDU_LEN'
 In file included from mt76-2019-07-22-75656a45/mt7603/../mt76.h:27:0,
                 from mt76-2019-07-22-75656a45/mt7603/mt7603.h:8,
                 from mt76-2019-07-22-75656a45/mt7603/pci.c:7:
 usr/include/mac80211/net/mac80211.h:2293:2: note: previous definition of 'IEEE80211_HW_REPORTS_TX_ACK_STATUS' was here
   IEEE80211_HW_REPORTS_TX_ACK_STATUS,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is caused by failing check-cc-enum build check due to the following
compile error:

 ./include/linux/dynamic_debug.h:77:14: error: 'KBUILD_MODNAME' undeclared (first use in this function); did you mean 'KERN_NODENAME'?
    .modname = KBUILD_MODNAME,   \

So this patch adds missing KBUILD_MODNAME variable to
CHECK_CC_ENUM_FLAGS in order to make check-cc-enum build check compile
again.

Ref: http://lists.infradead.org/pipermail/openwrt-devel/2019-August/018202.html
Fixes: c4e4982fa923 ("mt7603: set IEEE80211_HW_TX_STATUS_NO_AMPDU_LEN")
Cc: Felix Fietkau <nbd@nbd.name>
Reported-by: Joan Moreau <jom@grosjo.net>
Signed-off-by: Petr Štetiar <ynezz@true.cz>